version: 2
updates:
  - package-ecosystem: pip
    directory: /backend/guantou
    schedule:
      interval: daily
    rebase-strategy: auto
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: daily
    rebase-strategy: auto
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    rebase-strategy: auto
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci(deps)"
