# Generated by Django 6.1 on 2026-09-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0006_alter_notification_verb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("system.message", "系统消息"),
                    ("recording.like", "录音获赞"),
                    ("entry.comment", "词条有新评论"),
                    ("entry.reply", "词条评论有新回复"),
                    ("entry.comment_like", "词条评论获赞"),
                    ("recording.comment", "录音有新评论"),
                    ("recording.reply", "评论有新回复"),
                    ("comment.reply", "评论有新回复"),
                    ("recording.comment_like", "评论获赞"),
                    ("entry.bookmark", "词条获收藏"),
                    ("entry.usage_attestation", "词条获地区补证"),
                    ("recording.entry_link", "录音获词条关联"),
                    ("curation.review", "整理审核结果"),
                ],
                default="system.message",
                max_length=64,
            ),
        ),
    ]
