# Generated by Django 6.1 on 2026-09-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guantou", "0026_recordingcomment_reply_to"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="recordingcomment",
            index=models.Index(
                fields=["entry", "parent", "hidden", "created_at"],
                name="entry_comment_thread_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recordingcomment",
            index=models.Index(
                fields=["recording", "parent", "hidden", "created_at"],
                name="rec_comment_thread_idx",
            ),
        ),
    ]
